import { jsPDF } from "jspdf";
import { GeneratedItinerary } from "../types";

export const downloadItineraryPDF = (itinerary: GeneratedItinerary, locationName: string) => {
  const doc = new jsPDF();
  const margin = 20;
  let y = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const maxLineWidth = pageWidth - margin * 2;

  // Helper to add text and advance Y
  const addText = (text: string, fontSize: number, fontStyle: string = "normal", color: [number, number, number] = [0, 0, 0]) => {
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", fontStyle);
    doc.setTextColor(color[0], color[1], color[2]);
    
    const lines = doc.splitTextToSize(text, maxLineWidth);
    doc.text(lines, margin, y);
    y += lines.length * (fontSize * 0.4) + 6; // Line height spacing
    
    // Check for page break
    if (y > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      y = 20;
    }
  };

  // Header
  addText(`Yatra Travel Guide: ${locationName}`, 24, "bold", [13, 148, 136]); // Teal color
  y += 5;
  
  // Title & Overview
  addText(itinerary.title, 18, "bold");
  addText(itinerary.overview, 12, "italic", [80, 80, 80]);
  y += 10;
  
  // Line separator
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y - 5, pageWidth - margin, y - 5);

  // Days
  itinerary.days.forEach((day) => {
    addText(`Day ${day.day}`, 16, "bold", [15, 23, 42]); // Slate 900
    
    day.segments.forEach((segment) => {
      // Time & Title
      const header = `${segment.timeOfDay.toUpperCase()} - ${segment.title}`;
      addText(header, 12, "bold", [50, 50, 50]);
      
      // Details
      addText(segment.description, 10, "normal", [80, 80, 80]);
      
      if (segment.location) {
        addText(`Location: ${segment.location}`, 9, "italic", [100, 100, 100]);
        y -= 2; // Tighten spacing
      }
      
      if (segment.tips) {
        addText(`Tip: ${segment.tips}`, 9, "italic", [217, 119, 6]); // Amber
      }
      
      y += 5; // Spacing between segments
    });
    
    y += 5; // Spacing between days
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by Yatra AI - Page ${i} of ${pageCount}`, pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });
  }

  doc.save(`Yatra_${locationName}_Itinerary.pdf`);
};